
package br.com.moreira.jovencio.GerenciamentoAcessos.views.actionEvent.tabelaManterUsuarios;

import java.awt.event.ActionEvent;

/**
 *
 * @author marlan
 */
public class PanelActionTabelaManterUsuarios extends javax.swing.JPanel {

	/** Creates new form PanelAction */
	public PanelActionTabelaManterUsuarios() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVisualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNotificar = new javax.swing.JButton();
        btnAutorizar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(366, 40));

        btnVisualizar.setText("Visualizar");
        btnVisualizar.setPreferredSize(new java.awt.Dimension(120, 28));

        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(90, 28));

        btnNotificar.setText("Notificar");
        btnNotificar.setPreferredSize(new java.awt.Dimension(120, 28));

        btnAutorizar.setText("Autorizar");
        btnAutorizar.setPreferredSize(new java.awt.Dimension(120, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutorizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNotificar;
    private javax.swing.JButton btnVisualizar;
    // End of variables declaration//GEN-END:variables

	public void initEvent( IAcoesTabelaManterUsuario event, int row ) {
		btnAutorizar.addActionListener( ( ActionEvent e ) -> {
			event.autorizar( row );
		} );
		btnEditar.addActionListener( ( ActionEvent e ) -> {
			event.editar( row );
		} );
		btnNotificar.addActionListener( ( ActionEvent e ) -> {
			event.notificar( row );
		} );
		btnVisualizar.addActionListener( ( ActionEvent e ) -> {
			event.visualizar( row );
		} );
	}
}
