
package br.com.moreira.jovencio.GerenciamentoAcessos.views;

import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author marlan/eriani
 */
public class NotificacoesUsuarioView extends javax.swing.JInternalFrame {

	/** Creates new form NotificarUsuarioView */
	public NotificacoesUsuarioView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotificarUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotificacoes = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Notificações");

        lblNotificarUsuario.setText("Notificações do Usuário %s");

        tblNotificacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Lida?", "Data de Envio", "Mensagem", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNotificacoes.setFillsViewportHeight(true);
        tblNotificacoes.setRowHeight(40);
        jScrollPane2.setViewportView(tblNotificacoes);
        if (tblNotificacoes.getColumnModel().getColumnCount() > 0) {
            tblNotificacoes.getColumnModel().getColumn(0).setResizable(false);
            tblNotificacoes.getColumnModel().getColumn(0).setPreferredWidth(6);
            tblNotificacoes.getColumnModel().getColumn(1).setResizable(false);
            tblNotificacoes.getColumnModel().getColumn(1).setPreferredWidth(12);
            tblNotificacoes.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNotificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNotificarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNotificarUsuario;
    private javax.swing.JTable tblNotificacoes;
    // End of variables declaration//GEN-END:variables

	public JLabel getLblNotificarUsuario() {
		return lblNotificarUsuario;
	}

	public JTable getTblNotificacoes() {
		return tblNotificacoes;
	}

}
