
package br.com.moreira.jovencio.GerenciamentoAcessos.views;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JToolBar;

/**
 *
 * @author marlan/eriani
 */
public class PrincipalView extends javax.swing.JFrame {

	/** Creates new form PrincipalView */
	public PrincipalView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        toolBarFuncoes = new javax.swing.JToolBar();
        btnManterUsuarios = new javax.swing.JButton();
        btnNotificacoes = new javax.swing.JButton();
        btnAlteracaoSenha = new javax.swing.JButton();
        lblUsuarioLogado = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        toolBarFuncoes.setRollover(true);

        btnManterUsuarios.setText("Manter Usuários");
        btnManterUsuarios.setFocusable(false);
        btnManterUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManterUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarFuncoes.add(btnManterUsuarios);

        btnNotificacoes.setText("Notificações");
        btnNotificacoes.setFocusable(false);
        btnNotificacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotificacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarFuncoes.add(btnNotificacoes);

        btnAlteracaoSenha.setText("Alteração de senha");
        btnAlteracaoSenha.setFocusable(false);
        btnAlteracaoSenha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlteracaoSenha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBarFuncoes.add(btnAlteracaoSenha);

        lblUsuarioLogado.setText("Usuário: %s - %s");

        desktopPane.setLayer(toolBarFuncoes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblUsuarioLogado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBarFuncoes, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(lblUsuarioLogado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(toolBarFuncoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(lblUsuarioLogado))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteracaoSenha;
    private javax.swing.JButton btnManterUsuarios;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JToolBar toolBarFuncoes;
    // End of variables declaration//GEN-END:variables

	public JButton getBtnAlteracaoSenha() {
		return btnAlteracaoSenha;
	}

	public JButton getBtnManterUsuarios() {
		return btnManterUsuarios;
	}

	public JButton getBtnNotificacoes() {
		return btnNotificacoes;
	}

	public JDesktopPane getDesktopPane() {
		return desktopPane;
	}

	public JMenuItem getExitMenuItem() {
		return exitMenuItem;
	}

	public JToolBar getToolBarFuncoes() {
		return toolBarFuncoes;
	}

	public JLabel getLblUsuarioLogado() {
		return lblUsuarioLogado;
	}

}
