
package br.com.moreira.jovencio.GerenciamentoAcessos.views.actionEvent.tabelaNotificacoes;

import java.awt.event.ActionEvent;

/**
 *
 * @author marlan
 */
public class PanelActionTabelaNotificacoes extends javax.swing.JPanel {

	/** Creates new form PanelActionTabelaNotificacoes */
	public PanelActionTabelaNotificacoes() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLidaNaoLida = new javax.swing.JButton();

        btnLidaNaoLida.setText("Lida/Não Lida");
        btnLidaNaoLida.setPreferredSize(new java.awt.Dimension(160, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLidaNaoLida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnLidaNaoLida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLidaNaoLida;
    // End of variables declaration//GEN-END:variables

	public void initEvent( IAcoesTabelaNotificacoes event, int row ) {
		btnLidaNaoLida.addActionListener( ( ActionEvent e ) -> {
			event.lidaNaoLida( row );
		} );
	}
}
